#!/usr/bin/env python3
# MAINTENANCE: Rebuild the reader only from audited bilingual Knowledge Compendium pairs; keep it self-contained.
"""Build a single-file bilingual offline reader from the Knowledge Compendium."""
from __future__ import annotations
import json, re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
BASE=ROOT/'Offline Library'/'Knowledge Compendium'
OUT=ROOT/'Offline Survival Reader.html'
NUM=re.compile(r'^(\d+)-')

def parse_file(path:Path):
    text=path.read_text(encoding='utf-8').strip()
    lines=text.splitlines()
    title=lines[0].lstrip('#').strip() if lines else path.stem
    body='\n'.join(lines[1:]).strip()
    return title,body

def main():
    en={int(NUM.match(p.name).group(1)):p for p in (BASE/'EN').glob('*.md') if NUM.match(p.name) and int(NUM.match(p.name).group(1))>0}
    gr={int(NUM.match(p.name).group(1)):p for p in (BASE/'GR').glob('*.md') if NUM.match(p.name) and int(NUM.match(p.name).group(1))>0}
    if set(en)!=set(gr): raise SystemExit(f'Knowledge pairing mismatch: EN-only {sorted(set(en)-set(gr))}, GR-only {sorted(set(gr)-set(en))}')
    data=[]
    for n in sorted(en):
        et,eb=parse_file(en[n]); gt,gb=parse_file(gr[n])
        data.append({'id':n,'en':{'title':et,'body':eb},'el':{'title':gt,'body':gb}})
    payload=json.dumps(data,ensure_ascii=False,separators=(',',':')).replace('</','<\\/')
    html=TEMPLATE.replace('__CHAPTER_COUNT__',str(len(data))).replace('__DATA__',payload)
    OUT.write_text(html,encoding='utf-8')
    print(json.dumps({'output':str(OUT),'chapters':len(data),'bytes':OUT.stat().st_size},ensure_ascii=False))
TEMPLATE=r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="dark light"><title>Offline Survival Reader</title>
<style>
:root{--bg:#0b0e0c;--panel:#121713;--panel2:#19201b;--text:#edf6ef;--muted:#a8b8ab;--line:#304238;--accent:#86e29b;--warn:#ffd377}*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:var(--bg);color:var(--text);font:15px/1.55 system-ui,-apple-system,Segoe UI,Roboto,sans-serif}button,input,select{font:inherit}button,select,input{background:var(--panel2);color:var(--text);border:1px solid var(--line);border-radius:10px;padding:10px}button{cursor:pointer}button:hover{border-color:var(--accent)}a{color:var(--accent)}.app{min-height:100vh;display:grid;grid-template-columns:320px minmax(0,1fr)}aside{border-right:1px solid var(--line);padding:14px;position:sticky;top:0;height:100vh;overflow:auto;background:var(--panel)}main{padding:20px 24px;max-width:1050px;width:100%;margin:0 auto}.brand{font-weight:800;font-size:18px}.sub{color:var(--muted);font-size:12px}.controls{display:grid;gap:8px;margin:14px 0}.row{display:flex;gap:8px;flex-wrap:wrap}.row>*{flex:1}.list{display:grid;gap:6px}.chapterBtn{text-align:left;width:100%;padding:10px}.chapterBtn.active{border-color:var(--accent);background:#1c2b20}.chapterBtn small{display:block;color:var(--muted)}.top{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;flex-wrap:wrap;border-bottom:1px solid var(--line);padding-bottom:14px}.badge{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:4px 8px;font-size:12px;color:var(--accent)}article{padding-bottom:50px}article h1{font-size:clamp(26px,5vw,44px);line-height:1.08;margin:18px 0}article h2{font-size:22px;margin-top:30px}article h3{font-size:18px;margin-top:26px}article p{max-width:80ch}article li{margin:6px 0}.sourceNote{border-left:3px solid var(--warn);padding:8px 12px;background:var(--panel);color:var(--muted)}mark{background:#665714;color:white}.empty{color:var(--muted);padding:20px 0}.mobileTop{display:none;position:sticky;top:0;z-index:20;background:var(--bg);padding:8px 0;border-bottom:1px solid var(--line)}@media(max-width:800px){.app{display:block}aside{position:fixed;inset:0 8% 0 0;z-index:40;transform:translateX(-110%);transition:.2s;height:100vh;box-shadow:0 0 40px #000}.menuOpen aside{transform:none}.mobileTop{display:flex;gap:8px;align-items:center}main{padding:0 14px 24px}.mobileTop button{flex:0 0 auto}.mobileTop span{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.top{margin-top:8px}}@media print{aside,.mobileTop,.top .actions{display:none!important}.app{display:block}main{max-width:none;padding:0;background:white;color:black}body{background:white;color:black}.sourceNote{color:#333;background:#fff}}
</style></head><body><div class="app" id="app"><aside><div class="brand">Offline Survival Reader</div><div class="sub" id="offlineLabel">Single-file survival library · __CHAPTER_COUNT__ chapters · no internet required</div><div class="controls"><input id="q" type="search" placeholder="Search all chapters"><select id="domain"></select><div class="row"><button id="lang">Ελληνικά</button><button id="favOnly">★ Favorites</button></div><div class="row"><button id="clear">Clear</button><button id="closeMenu">Close menu</button></div></div><div class="sub" id="count"></div><div class="list" id="list"></div></aside><main><div class="mobileTop"><button id="menu">☰</button><span id="mobileTitle">Offline Survival Reader</span></div><div class="top"><div><span class="badge" id="status">OFFLINE · LOCAL FILE</span><div class="sub" id="privacy">All knowledge is embedded in this HTML file. Searches and favorites stay in this browser.</div></div><div class="actions row"><button id="favorite">☆ Favorite</button><button id="reviewed">✓ Reviewed</button><button id="print">Print chapter</button></div></div><article id="article"></article></main></div>
<script>const CHAPTERS=__DATA__;</script><script>
'use strict';(()=>{const $=id=>document.getElementById(id),app=$('app');let lang=(localStorage.getItem('osp-reader-lang')||((navigator.language||'').toLowerCase().startsWith('el')?'el':'en'));let current=Number(localStorage.getItem('osp-reader-current')||1);let fav=new Set(JSON.parse(localStorage.getItem('osp-reader-fav')||'[]'));let reviewed=new Set(JSON.parse(localStorage.getItem('osp-reader-reviewed')||'[]'));let onlyFav=false;
const T={en:{offline:`Single-file survival library · ${CHAPTERS.length} chapters · no internet required`,search:'Search all chapters',fav:'★ Favorites',all:'All knowledge',water:'Water / food / sanitation',medical:'Medical continuity / first aid',hazards:'Fire / earthquake / weather',nav:'Navigation / communications / recovery',greece:'Greece-specific',resilience:'Household resilience',infra:'Infrastructure / long outage',advanced:'Advanced operational safety',urgent:'Recognition / rescue / fire',systems:'Power / water / food / shelter',global:'Global hazard supplement',clear:'Clear',close:'Close menu',privacy:'All knowledge is embedded in this HTML file. Searches and favorites stay in this browser.',favorite:'☆ Favorite',favorited:'★ Favorited',reviewed:'✓ Reviewed',markReview:'✓ Mark reviewed',print:'Print chapter',no:'No chapters match this filter.',count:n=>`${n} chapter${n===1?'':'s'}`,source:'Source URLs are stored for verification when connectivity is available; the survival guidance itself is contained offline.'},el:{offline:`Μονοαρχείος οδηγός επιβίωσης · ${CHAPTERS.length} κεφάλαια · χωρίς ανάγκη διαδικτύου`,search:'Αναζήτηση σε όλα τα κεφάλαια',fav:'★ Αγαπημένα',all:'Όλη η γνώση',water:'Νερό / τρόφιμα / υγιεινή',medical:'Ιατρική συνέχεια / πρώτες βοήθειες',hazards:'Φωτιά / σεισμός / καιρός',nav:'Πλοήγηση / επικοινωνίες / αποκατάσταση',greece:'Ειδικά για Ελλάδα',resilience:'Ανθεκτικότητα νοικοκυριού',infra:'Υποδομές / μεγάλη διακοπή',advanced:'Προχωρημένη επιχειρησιακή ασφάλεια',urgent:'Αναγνώριση / διάσωση / φωτιά',systems:'Ρεύμα / νερό / τρόφιμα / καταφύγιο',global:'Παγκόσμιο συμπλήρωμα κινδύνων',clear:'Καθαρισμός',close:'Κλείσιμο μενού',privacy:'Όλη η γνώση βρίσκεται μέσα σε αυτό το HTML. Οι αναζητήσεις και τα αγαπημένα μένουν σε αυτόν τον browser.',favorite:'☆ Αγαπημένο',favorited:'★ Αγαπημένο',reviewed:'✓ Διαβασμένο',markReview:'✓ Σήμανση ως διαβασμένο',print:'Εκτύπωση κεφαλαίου',no:'Δεν υπάρχει κεφάλαιο με αυτά τα φίλτρα.',count:n=>`${n} κεφάλαια`,source:'Οι διευθύνσεις πηγών αποθηκεύονται για μελλοντική επαλήθευση όταν υπάρχει σύνδεση· η ίδια η καθοδήγηση επιβίωσης βρίσκεται αποθηκευμένη τοπικά.'}};
const ranges=[['all',1,999],['water',1,14],['medical',15,21],['hazards',22,32],['nav',33,40],['greece',41,48],['resilience',49,80],['infra',81,127],['advanced',128,160],['urgent',161,180],['systems',181,200],['global',201,220]];
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}function save(){localStorage.setItem('osp-reader-lang',lang);localStorage.setItem('osp-reader-current',String(current));localStorage.setItem('osp-reader-fav',JSON.stringify([...fav]));localStorage.setItem('osp-reader-reviewed',JSON.stringify([...reviewed]));}
function md(text){const out=[];let inList=false;for(const raw of text.split(/\r?\n/)){const line=raw.trim();if(!line){if(inList){out.push('</ul>');inList=false}continue}if(line.startsWith('## ')){if(inList){out.push('</ul>');inList=false}out.push(`<h2>${esc(line.slice(3))}</h2>`)}else if(line.startsWith('### ')){if(inList){out.push('</ul>');inList=false}out.push(`<h3>${esc(line.slice(4))}</h3>`)}else if(/^[-*] /.test(line)){if(!inList){out.push('<ul>');inList=true}out.push(`<li>${esc(line.slice(2))}</li>`)}else{if(inList){out.push('</ul>');inList=false}out.push(`<p>${esc(line)}</p>`)}}if(inList)out.push('</ul>');return out.join('')}
function setupDomains(){const d=$('domain'),old=d.value||'all';d.innerHTML=ranges.map(([k])=>`<option value="${k}">${esc(T[lang][k])}</option>`).join('');d.value=old}
function filtered(){const q=$('q').value.trim().toLocaleLowerCase(lang==='el'?'el':'en'),r=ranges.find(x=>x[0]===$('domain').value)||ranges[0];return CHAPTERS.filter(c=>{if(c.id<r[1]||c.id>r[2]||onlyFav&&!fav.has(c.id))return false;if(!q)return true;const x=c[lang];return `${x.title}\n${x.body}`.toLocaleLowerCase(lang==='el'?'el':'en').includes(q)})}
function renderList(){const a=filtered();$('count').textContent=T[lang].count(a.length);$('list').innerHTML=a.map(c=>`<button class="chapterBtn ${c.id===current?'active':''}" data-id="${c.id}"><small>${String(c.id).padStart(3,'0')} ${reviewed.has(c.id)?'✓':''}${fav.has(c.id)?' ★':''}</small>${esc(c[lang].title)}</button>`).join('')||`<div class="empty">${esc(T[lang].no)}</div>`;document.querySelectorAll('.chapterBtn').forEach(b=>b.onclick=()=>{current=Number(b.dataset.id);save();render();app.classList.remove('menuOpen')})}
function renderArticle(){let c=CHAPTERS.find(x=>x.id===current)||CHAPTERS[0];current=c.id;const x=c[lang];$('article').innerHTML=`<h1><span class="badge">${String(c.id).padStart(3,'0')}</span><br>${esc(x.title)}</h1><div class="sourceNote">${esc(T[lang].source)}</div>${md(x.body)}`;$('mobileTitle').textContent=`${c.id}. ${x.title}`;$('favorite').textContent=fav.has(c.id)?T[lang].favorited:T[lang].favorite;$('reviewed').textContent=reviewed.has(c.id)?T[lang].reviewed:T[lang].markReview;document.title=`${c.id}. ${x.title} — Offline Survival Reader`;save()}
function labels(){$('offlineLabel').textContent=T[lang].offline;$('q').placeholder=T[lang].search;$('favOnly').textContent=T[lang].fav;$('clear').textContent=T[lang].clear;$('closeMenu').textContent=T[lang].close;$('privacy').textContent=T[lang].privacy;$('print').textContent=T[lang].print;$('lang').textContent=lang==='en'?'Ελληνικά':'English';setupDomains()}
function render(){labels();renderList();renderArticle()}
$('q').oninput=renderList;$('domain').onchange=renderList;$('lang').onclick=()=>{lang=lang==='en'?'el':'en';save();render()};$('favOnly').onclick=()=>{onlyFav=!onlyFav;$('favOnly').style.borderColor=onlyFav?'var(--accent)':'';renderList()};$('favorite').onclick=()=>{fav.has(current)?fav.delete(current):fav.add(current);save();render()};$('reviewed').onclick=()=>{reviewed.has(current)?reviewed.delete(current):reviewed.add(current);save();render()};$('print').onclick=()=>print();$('clear').onclick=()=>{$('q').value='';$('domain').value='all';onlyFav=false;renderList()};$('menu').onclick=()=>app.classList.add('menuOpen');$('closeMenu').onclick=()=>app.classList.remove('menuOpen');addEventListener('keydown',e=>{if(e.key==='Escape')app.classList.remove('menuOpen')});render();})();
</script></body></html>'''
if __name__=='__main__': main()
