/* MAINTENANCE: Derived decision support only. It reads existing local registers and does not invent emergency thresholds. */
Object.assign(T.en,{
 missioncontrol:'Mission control',missioncontrolSub:'Turn existing local registers into a compact list of unresolved operational exceptions.',missioncontrolTitle:'Mission control',missioncontrolText:'A derived view of dependencies, triggers, mutual-aid needs and resource losses. It creates no new hidden state.',decisionSafety:'Decision support summarizes your own records. It does not predict hazards, diagnose safety, or override official alerts, emergency services or qualified professional guidance.',decisionOpenGaps:'Open gaps',decisionCritical:'Critical',decisionFallbacks:'Fallback gaps',decisionSignals:'Action signals',decisionCurrent:'Current priorities',decisionNone:'No unresolved priorities can be derived from the current registers.',openGapMatrix:'Open gap matrix',openFirst24:'Open first 24 hours',openSustainment:'Open sustainment review',openAfterAction:'Open after-action review',exportBrief:'Export brief',
 gapmatrix:'Gap matrix',gapmatrixSub:'Rank unresolved dependencies, met triggers, open aid needs and recorded losses by transparent local rules.',gapmatrixTitle:'Prioritized gap matrix',gapmatrixText:'Every row names the register that produced it, the reason it is open and the next coordination action already implied by your data.',gapRank:'Rank',gapSeverity:'Severity',gapSource:'Source',gapIssue:'Issue',gapAction:'Coordination action',critical:'Critical',high:'High',moderate:'Moderate',
 first24:'First 24 h',first24Sub:'Sequence current gaps into immediate, near-term and sustainment review windows without inventing hazard-specific thresholds.',first24Title:'First-24-hours sequence',first24Text:'This view groups current exceptions by urgency so the team can work from one visible order and revisit it as conditions change.',phaseImmediate:'Now · verify and protect',phaseHour:'Next hour · establish fallbacks',phaseSix:'1–6 h · stabilize continuity',phaseDay:'6–24 h · sustain and hand over',phaseEmpty:'No item currently falls into this phase.',exportSequence:'Export sequence',
 sustainment:'Sustainment',sustainmentSub:'Compare actual resource movements and unresolved dependencies so short-term workarounds do not silently become long-term assumptions.',sustainmentTitle:'Sustainment review',sustainmentText:'A factual review of resources moved, fallback coverage and open support needs. Amounts are shown exactly as entered and units are never mixed.',movement24:'Movements · 24 h',movement7:'Movements · 7 d',resourcesMoved:'Resources moved',openNeedsLabel:'Open needs',resourceBalance:'Observed resource movement',movementNet:'Observed net',movementNote:'Positive values are restocks; use, loss and transfer are negative. This is bookkeeping, not a safe consumption target.',
 afteraction:'After action',afteractionSub:'Close the loop by showing what recovered, what was acted on and which gaps still need a permanent change.',afteractionTitle:'After-action review',afteractionText:'Use the evidence already in the local registers to capture lessons before temporary workarounds become forgotten assumptions.',restoredDependencies:'Dependencies restored',actedTriggers:'Triggers acted / closed',completedAid:'Aid matched / completed',remainingGaps:'Remaining gaps',afterEvidence:'Evidence for review',afterLessonFallback:'Dependencies still missing a fallback',afterLessonLoss:'Resources recorded as lost',afterLessonTrigger:'Triggers that required action',afterNoEvidence:'No after-action evidence has been recorded yet.',exportAfterAction:'Export review'
});
Object.assign(T.el,{
 missioncontrol:'Κέντρο αποστολής',missioncontrolSub:'Μετέτρεψε τις υπάρχουσες τοπικές καταγραφές σε συμπαγή λίστα ανεπίλυτων επιχειρησιακών εξαιρέσεων.',missioncontrolTitle:'Κέντρο αποστολής',missioncontrolText:'Παράγωγη προβολή εξαρτήσεων, ενεργοποιήσεων, αναγκών αλληλοβοήθειας και απωλειών πόρων. Δεν δημιουργεί κρυφή νέα κατάσταση.',decisionSafety:'Η υποστήριξη αποφάσεων συνοψίζει τις δικές σου καταγραφές. Δεν προβλέπει κινδύνους, δεν κρίνει ασφάλεια και δεν υπερισχύει επίσημων ειδοποιήσεων, υπηρεσιών έκτακτης ανάγκης ή κατάλληλης επαγγελματικής καθοδήγησης.',decisionOpenGaps:'Ανοιχτά κενά',decisionCritical:'Κρίσιμα',decisionFallbacks:'Κενά εφεδρείας',decisionSignals:'Σήματα ενέργειας',decisionCurrent:'Τρέχουσες προτεραιότητες',decisionNone:'Δεν προκύπτουν ανεπίλυτες προτεραιότητες από τις τρέχουσες καταγραφές.',openGapMatrix:'Άνοιγμα πίνακα κενών',openFirst24:'Άνοιγμα πρώτων 24 ωρών',openSustainment:'Άνοιγμα ανασκόπησης συνέχειας',openAfterAction:'Άνοιγμα αποτίμησης',exportBrief:'Εξαγωγή σύνοψης',
 gapmatrix:'Πίνακας κενών',gapmatrixSub:'Ιεράρχησε ανεπίλυτες εξαρτήσεις, ενεργοποιημένα όρια, ανοιχτές ανάγκες και καταγεγραμμένες απώλειες με διαφανείς τοπικούς κανόνες.',gapmatrixTitle:'Ιεραρχημένος πίνακας κενών',gapmatrixText:'Κάθε γραμμή δείχνει το μητρώο προέλευσης, γιατί παραμένει ανοιχτή και την επόμενη ενέργεια συντονισμού που προκύπτει από τα δεδομένα σου.',gapRank:'Σειρά',gapSeverity:'Βαρύτητα',gapSource:'Πηγή',gapIssue:'Θέμα',gapAction:'Ενέργεια συντονισμού',critical:'Κρίσιμο',high:'Υψηλό',moderate:'Μέτριο',
 first24:'Πρώτες 24 ωρ.',first24Sub:'Ταξινόμησε τα τρέχοντα κενά σε άμεσο, κοντινό και παρατεταμένο επανέλεγχο χωρίς επινοημένα όρια κινδύνου.',first24Title:'Ακολουθία πρώτων 24 ωρών',first24Text:'Η προβολή ομαδοποιεί τις τρέχουσες εξαιρέσεις κατά προτεραιότητα ώστε η ομάδα να δουλεύει από μία ορατή σειρά και να την αναθεωρεί όταν αλλάζουν οι συνθήκες.',phaseImmediate:'Τώρα · επιβεβαίωση και προστασία',phaseHour:'Επόμενη ώρα · εφεδρείες',phaseSix:'1–6 ωρ. · σταθεροποίηση συνέχειας',phaseDay:'6–24 ωρ. · διατήρηση και παράδοση',phaseEmpty:'Δεν υπάρχει τρέχον στοιχείο σε αυτή τη φάση.',exportSequence:'Εξαγωγή ακολουθίας',
 sustainment:'Διατήρηση',sustainmentSub:'Σύγκρινε πραγματικές κινήσεις πόρων και ανεπίλυτες εξαρτήσεις ώστε προσωρινές λύσεις να μη γίνουν σιωπηρές μόνιμες υποθέσεις.',sustainmentTitle:'Ανασκόπηση διατήρησης',sustainmentText:'Πραγματολογική ανασκόπηση κίνησης πόρων, κάλυψης εφεδρειών και ανοιχτών αναγκών. Οι ποσότητες εμφανίζονται όπως καταγράφηκαν και διαφορετικές μονάδες δεν αναμειγνύονται.',movement24:'Κινήσεις · 24 ωρ.',movement7:'Κινήσεις · 7 ημ.',resourcesMoved:'Πόροι σε κίνηση',openNeedsLabel:'Ανοιχτές ανάγκες',resourceBalance:'Παρατηρημένη κίνηση πόρων',movementNet:'Παρατηρημένο ισοζύγιο',movementNote:'Θετικές τιμές είναι αναπληρώσεις· χρήση, απώλεια και μεταφορά είναι αρνητικές. Είναι λογιστική καταγραφή, όχι ασφαλής στόχος κατανάλωσης.',
 afteraction:'Αποτίμηση',afteractionSub:'Κλείσε τον κύκλο δείχνοντας τι αποκαταστάθηκε, πού έγινε ενέργεια και ποια κενά χρειάζονται μόνιμη αλλαγή.',afteractionTitle:'Αποτίμηση μετά το συμβάν',afteractionText:'Χρησιμοποίησε τα στοιχεία των τοπικών μητρώων για να κρατήσεις τα μαθήματα πριν οι προσωρινές λύσεις γίνουν ξεχασμένες υποθέσεις.',restoredDependencies:'Εξαρτήσεις που αποκαταστάθηκαν',actedTriggers:'Ενεργοποιήσεις με ενέργεια / κλείσιμο',completedAid:'Βοήθεια που αντιστοιχίστηκε / ολοκληρώθηκε',remainingGaps:'Κενά που απομένουν',afterEvidence:'Στοιχεία για ανασκόπηση',afterLessonFallback:'Εξαρτήσεις που ακόμη δεν έχουν εφεδρεία',afterLessonLoss:'Πόροι που καταγράφηκαν ως απώλεια',afterLessonTrigger:'Ενεργοποιήσεις που απαίτησαν ενέργεια',afterNoEvidence:'Δεν έχουν ακόμη καταγραφεί στοιχεία αποτίμησης.',exportAfterAction:'Εξαγωγή αποτίμησης'
});

const DECISION_NAV=[['missioncontrol','◉'],['gapmatrix','△'],['first24','24'],['sustainment','∞'],['afteraction','↺']];
const decisionAt=NAV.findIndex(x=>x[0]==='resilience');
if(decisionAt>=0&&!NAV.some(x=>x[0]==='missioncontrol'))NAV.splice(decisionAt,0,...DECISION_NAV);
DECISION_NAV.forEach(x=>{if(!MOBILE_NAV.includes(x[0])){const at=MOBILE_NAV.indexOf('resilience');MOBILE_NAV.splice(at<0?MOBILE_NAV.length:at,0,x[0])}});

function decisionGaps(){
 const out=[]; let order=0;
 const push=(severity,source,issue,action,section)=>out.push({severity,source,issue,action,section,order:order++});
 (state.dependencies||[]).forEach(x=>{if(x.status==='failed')push(3,tx('dependencies'),`${x.system}: ${x.dependency}`,x.fallback||tx('dependencyNoFallback'),'dependencies');else if(x.status==='degraded')push(2,tx('dependencies'),`${x.system}: ${x.dependency}`,x.fallback||tx('dependencyNoFallback'),'dependencies');else if(!x.fallback&&x.status!=='restored')push(2,tx('dependencies'),`${x.system}: ${tx('dependencyNoFallback')}`,x.dependency,'dependencies')});
 (state.action_triggers||[]).forEach(x=>{if(x.status==='met')push(3,tx('triggers'),x.name,x.action,'triggers');else if(x.status==='watch'&&typeof resilienceDue==='function'&&resilienceDue(x.review))push(2,tx('triggers'),x.name,x.action,'triggers')});
 (state.mutual_aid||[]).forEach(x=>{if(x.direction==='need'&&x.status==='open')push(2,tx('mutualaid'),x.capability,x.contact||x.quantity||tx('mutualNeed'),'mutualaid')});
 (state.consumption_log||[]).forEach(x=>{if(x.direction==='loss')push(2,tx('consumption'),`${x.resource}: ${x.amount} ${x.unit||''}`.trim(),x.context||tx('resourceLoss'),'consumption')});
 return out.sort((a,b)=>b.severity-a.severity||a.order-b.order);
}
function severityText(n){return tx(n===3?'critical':n===2?'high':'moderate')}
function decisionList(rows){return rows.length?`<ol>${rows.map(x=>`<li><strong>${esc(severityText(x.severity))}</strong> · ${esc(x.issue)} — ${esc(x.action||'—')} <button class="btn small" onclick="go('${x.section}')">${esc(x.source)}</button></li>`).join('')}</ol>`:`<div class="empty">${esc(tx('decisionNone'))}</div>`}
function renderMissionControl(){const gaps=decisionGaps(),root=$('#missionControlPriorities'),sum=$('#missionControlSummary');if(!root||!sum)return;const critical=gaps.filter(x=>x.severity===3).length,fallback=(state.dependencies||[]).filter(x=>!x.fallback&&x.status!=='restored').length,signals=(state.action_triggers||[]).filter(x=>x.status==='met').length;sum.innerHTML=`<div class="mini-stat"><small>${esc(tx('decisionOpenGaps'))}</small><strong>${fmt(gaps.length)}</strong></div><div class="mini-stat"><small>${esc(tx('decisionCritical'))}</small><strong>${fmt(critical)}</strong></div><div class="mini-stat"><small>${esc(tx('decisionFallbacks'))}</small><strong>${fmt(fallback)}</strong></div><div class="mini-stat"><small>${esc(tx('decisionSignals'))}</small><strong>${fmt(signals)}</strong></div>`;root.innerHTML=decisionList(gaps.slice(0,12))}
function renderGapMatrix(){const root=$('#gapMatrixTable');if(!root)return;const rows=decisionGaps();if(!rows.length){root.innerHTML=`<div class="empty">${esc(tx('decisionNone'))}</div>`;return}root.innerHTML=`<div class="table-wrap"><table class="data-table"><thead><tr><th>${esc(tx('gapRank'))}</th><th>${esc(tx('gapSeverity'))}</th><th>${esc(tx('gapSource'))}</th><th>${esc(tx('gapIssue'))}</th><th>${esc(tx('gapAction'))}</th></tr></thead><tbody>${rows.map((x,i)=>`<tr><td>${i+1}</td><td class="${x.severity===3?'status-bad':''}">${esc(severityText(x.severity))}</td><td>${esc(x.source)}</td><td><strong>${esc(x.issue)}</strong></td><td>${esc(x.action||'—')}</td></tr>`).join('')}</tbody></table></div>`}
function first24Groups(){const gaps=decisionGaps();return [gaps.filter(x=>x.severity===3),gaps.filter(x=>x.severity===2&&x.section==='dependencies'),gaps.filter(x=>x.severity===2&&x.section!=='dependencies'),gaps.filter(x=>x.severity<2)]}
function renderFirst24(){const root=$('#first24Phases');if(!root)return;const names=['phaseImmediate','phaseHour','phaseSix','phaseDay'],groups=first24Groups();root.innerHTML=groups.map((rows,i)=>`<div class="card panel-pad"><h3>${esc(tx(names[i]))}</h3>${rows.length?decisionList(rows):`<div class="empty">${esc(tx('phaseEmpty'))}</div>`}</div>`).join('')}
function movementRows(){const m=new Map();(state.consumption_log||[]).forEach(x=>{const key=`${String(x.resource||'').trim()}\u0000${String(x.unit||'').trim()}`;if(!m.has(key))m.set(key,{resource:x.resource,unit:x.unit||'',net:0,count:0});const r=m.get(key),v=Number(x.amount)||0;r.net+=(x.direction==='restock'?v:-v);r.count++});return [...m.values()].sort((a,b)=>String(a.resource).localeCompare(String(b.resource)))}
function movementRecent(hours){const cut=Date.now()-hours*3600000;return (state.consumption_log||[]).filter(x=>new Date(x.time).getTime()>=cut).length}
function renderSustainment(){const sum=$('#sustainmentSummary'),root=$('#sustainmentTable');if(!sum||!root)return;const rows=movementRows(),needs=(state.mutual_aid||[]).filter(x=>x.direction==='need'&&x.status==='open').length;sum.innerHTML=`<div class="mini-stat"><small>${esc(tx('movement24'))}</small><strong>${fmt(movementRecent(24))}</strong></div><div class="mini-stat"><small>${esc(tx('movement7'))}</small><strong>${fmt(movementRecent(168))}</strong></div><div class="mini-stat"><small>${esc(tx('resourcesMoved'))}</small><strong>${fmt(rows.length)}</strong></div><div class="mini-stat"><small>${esc(tx('openNeedsLabel'))}</small><strong>${fmt(needs)}</strong></div>`;root.innerHTML=rows.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>${esc(tx('resourceName'))}</th><th>${esc(tx('movementNet'))}</th><th>${esc(tx('consumptionEntries'))}</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${esc(x.resource)}</strong></td><td>${fmt(x.net,2)} ${esc(x.unit)}</td><td>${fmt(x.count)}</td></tr>`).join('')}</tbody></table></div><p class="muted">${esc(tx('movementNote'))}</p>`:`<div class="empty">${esc(tx('noConsumption'))}</div>`}
function renderAfterAction(){const sum=$('#afterActionSummary'),root=$('#afterActionEvidence');if(!sum||!root)return;const restored=(state.dependencies||[]).filter(x=>x.status==='restored').length,acted=(state.action_triggers||[]).filter(x=>['acted','closed'].includes(x.status)).length,aid=(state.mutual_aid||[]).filter(x=>['matched','completed'].includes(x.status)).length,gaps=decisionGaps(),fallback=(state.dependencies||[]).filter(x=>!x.fallback&&x.status!=='restored'),losses=(state.consumption_log||[]).filter(x=>x.direction==='loss'),triggered=(state.action_triggers||[]).filter(x=>['met','acted','closed'].includes(x.status));sum.innerHTML=`<div class="mini-stat"><small>${esc(tx('restoredDependencies'))}</small><strong>${fmt(restored)}</strong></div><div class="mini-stat"><small>${esc(tx('actedTriggers'))}</small><strong>${fmt(acted)}</strong></div><div class="mini-stat"><small>${esc(tx('completedAid'))}</small><strong>${fmt(aid)}</strong></div><div class="mini-stat"><small>${esc(tx('remainingGaps'))}</small><strong>${fmt(gaps.length)}</strong></div>`;const lines=[];fallback.forEach(x=>lines.push(`${tx('afterLessonFallback')}: ${x.system}`));losses.forEach(x=>lines.push(`${tx('afterLessonLoss')}: ${x.resource} · ${x.amount} ${x.unit||''}`));triggered.forEach(x=>lines.push(`${tx('afterLessonTrigger')}: ${x.name}`));root.innerHTML=lines.length?`<ul>${lines.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:`<div class="empty">${esc(tx('afterNoEvidence'))}</div>`}
function renderDecisionSupport(){renderMissionControl();renderGapMatrix();renderFirst24();renderSustainment();renderAfterAction()}
function decisionText(title,lines){downloadBlob(`${title}\n${'='.repeat(title.length)}\n${lines.join('\n')}\n`,`offline-survival-${title.toLowerCase().replace(/[^a-z0-9]+/g,'-')}.txt`,'text/plain;charset=utf-8')}
function exportDecisionBrief(){const g=decisionGaps();decisionText(tx('missioncontrolTitle'),g.map((x,i)=>`${i+1}. [${severityText(x.severity)}] ${x.source}: ${x.issue} -> ${x.action||'-'}`))}
function exportGapMatrixCSV(){const g=decisionGaps();downloadBlob(csvRows([['rank','severity','source','issue','action'],...g.map((x,i)=>[i+1,severityText(x.severity),x.source,x.issue,x.action])]),'offline-survival-gap-matrix.csv','text/csv;charset=utf-8')}
function exportFirst24Text(){const names=['phaseImmediate','phaseHour','phaseSix','phaseDay'];const lines=[];first24Groups().forEach((g,i)=>{lines.push(`\n${tx(names[i])}`);g.forEach(x=>lines.push(`- ${x.issue}: ${x.action||'-'}`))});decisionText(tx('first24Title'),lines)}
function exportSustainmentCSV(){downloadBlob(csvRows([['resource','unit','observed_net','entries'],...movementRows().map(x=>[x.resource,x.unit,x.net,x.count])]),'offline-survival-sustainment.csv','text/csv;charset=utf-8')}
function exportAfterActionText(){const g=decisionGaps();decisionText(tx('afteractionTitle'),[`${tx('remainingGaps')}: ${g.length}`,...g.map(x=>`- ${x.source}: ${x.issue}`)])}

const decisionBaseApplyLang=applyLang;applyLang=function(){decisionBaseApplyLang();renderDecisionSupport()};
const decisionBaseSetTitle=setTitle;setTitle=function(id){decisionBaseSetTitle(id);const subs={missioncontrol:'missioncontrolSub',gapmatrix:'gapmatrixSub',first24:'first24Sub',sustainment:'sustainmentSub',afteraction:'afteractionSub'};if(subs[id])$('#pageSub').textContent=tx(subs[id])};
const decisionBaseGo=go;go=function(id){decisionBaseGo(id);if(DECISION_NAV.some(x=>x[0]===id))renderDecisionSupport()};
applyLang();
