/* Offline Survival Project v7 Knowledge Atlas. No external dependencies. */
Object.assign(T.en,{
 knowledge:'Knowledge',knowledgeSub:'Deep offline manuals, local full-text search, and household review tracking.',knowledgeTitle:'Knowledge Atlas',knowledgeText:'Navigate the deep bilingual V7 compendium by operational domain, search its full text locally, and track what your household has actually reviewed.',openKnowledgeIndex:'Open compendium index',standaloneReader:'Standalone offline reader',refreshKnowledge:'Refresh atlas',knowledgeDomainsTitle:'Operational domains',knowledgeDomainsText:'Start with the hazard or capability you need; every result remains on this device.',knowledgeSearchTitle:'Search the compendium',knowledgeSearchText:'Full-text search covers the V7 manuals in the selected language.',knowledgeSearchPlaceholder:'Search water, wildfire, evacuation, power...',searchKnowledge:'Search knowledge',knowledgeRecommendedTitle:'Recommended from your Risk Board',knowledgeRecommendedText:'A local reading queue derived from the hazards you selected. It never sends the risk profile anywhere.',knowledgeRecommendedNone:'Select hazards on the Risk Board to build a focused reading queue.',knowledgeRiskCoverage:'Risk reading coverage',exportKnowledgeQueue:'Export reading queue',knowledgeQueueTitle:'Offline Survival — Risk reading queue',knowledgeQueueRisks:'Selected risks',knowledgeQueueEmpty:'No risk-linked chapters are currently recommended.',knowledgeProgressTitle:'Review progress',knowledgeProgressText:'Mark chapters reviewed or set them aside for a later drill. Status is stored only in the local state file.',knowledgeChapters:'V7 chapters',knowledgeReviewed:'Reviewed',knowledgeLater:'Review later',knowledgeUnreviewed:'Not reviewed',markReviewed:'Mark reviewed',markLater:'Review later',clearReview:'Clear status',knowledgeNoResults:'No matching V7 chapters.',knowledgeNeedQuery:'Enter at least 2 characters.',knowledgeWater:'Water & WASH',knowledgeFood:'Food',knowledgeMedical:'Medical continuity',knowledgeCare:'Infants & chronic care',knowledgeHazmat:'Radiation & hazardous releases',knowledgeInfrastructure:'Utilities & restoration',knowledgeHousehold:'Household routines',knowledgeFire:'Fire & smoke',knowledgeEarth:'Earthquake & tsunami',knowledgeWeather:'Weather & climate',knowledgePower:'Power',knowledgeNavigation:'Navigation & evacuation',knowledgePeople:'People & animals',knowledgeRecovery:'Recovery',knowledgeGreece:'Greece-specific',knowledgeMethod:'Source methodology'
});
Object.assign(T.el,{
 knowledge:'Γνώση',knowledgeSub:'Αναλυτικά εγχειρίδια χωρίς σύνδεση, τοπική αναζήτηση κειμένου και παρακολούθηση μελέτης.',knowledgeTitle:'Άτλας Γνώσης',knowledgeText:'Πλοηγήσου στην αναλυτική δίγλωσση συλλογή V7 ανά επιχειρησιακό τομέα, αναζήτησε το πλήρες κείμενο τοπικά και κατέγραψε τι έχει πράγματι μελετήσει το νοικοκυριό.',openKnowledgeIndex:'Άνοιγμα ευρετηρίου συλλογής',standaloneReader:'Αυτόνομος αναγνώστης χωρίς σύνδεση',refreshKnowledge:'Ανανέωση άτλαντα',knowledgeDomainsTitle:'Επιχειρησιακοί τομείς',knowledgeDomainsText:'Ξεκίνα από τον κίνδυνο ή τη δυνατότητα που χρειάζεσαι· κάθε αποτέλεσμα παραμένει στη συσκευή.',knowledgeSearchTitle:'Αναζήτηση στη συλλογή',knowledgeSearchText:'Η αναζήτηση πλήρους κειμένου καλύπτει τα εγχειρίδια V7 στην επιλεγμένη γλώσσα.',knowledgeSearchPlaceholder:'Αναζήτησε νερό, πυρκαγιά, εκκένωση, ενέργεια...',searchKnowledge:'Αναζήτηση γνώσης',knowledgeRecommendedTitle:'Προτεινόμενα από τον Πίνακα Κινδύνων',knowledgeRecommendedText:'Τοπική σειρά μελέτης που προκύπτει από τους κινδύνους που επέλεξες. Το προφίλ κινδύνου δεν αποστέλλεται πουθενά.',knowledgeRecommendedNone:'Επίλεξε κινδύνους στον Πίνακα Κινδύνων για στοχευμένη σειρά μελέτης.',knowledgeRiskCoverage:'Κάλυψη μελέτης κινδύνων',exportKnowledgeQueue:'Εξαγωγή σειράς μελέτης',knowledgeQueueTitle:'Offline Survival — σειρά μελέτης κινδύνων',knowledgeQueueRisks:'Επιλεγμένοι κίνδυνοι',knowledgeQueueEmpty:'Δεν υπάρχουν αυτή τη στιγμή προτεινόμενα κεφάλαια που να συνδέονται με τους επιλεγμένους κινδύνους.',knowledgeProgressTitle:'Πρόοδος μελέτης',knowledgeProgressText:'Σήμανε κεφάλαια ως μελετημένα ή για επόμενη άσκηση. Η κατάσταση αποθηκεύεται μόνο στο τοπικό αρχείο.',knowledgeChapters:'Κεφάλαια V7',knowledgeReviewed:'Μελετημένα',knowledgeLater:'Για αργότερα',knowledgeUnreviewed:'Χωρίς μελέτη',markReviewed:'Σήμανση ως μελετημένο',markLater:'Για αργότερα',clearReview:'Καθαρισμός κατάστασης',knowledgeNoResults:'Δεν βρέθηκαν αντίστοιχα κεφάλαια V7.',knowledgeNeedQuery:'Γράψε τουλάχιστον 2 χαρακτήρες.',knowledgeWater:'Νερό & υγιεινή',knowledgeFood:'Τρόφιμα',knowledgeMedical:'Ιατρική συνέχεια',knowledgeCare:'Βρέφη & χρόνια φροντίδα',knowledgeHazmat:'Ραδιολογικά & επικίνδυνες διαρροές',knowledgeInfrastructure:'Δίκτυα & επαναφορά',knowledgeHousehold:'Ρουτίνες νοικοκυριού',knowledgeFire:'Φωτιά & καπνός',knowledgeEarth:'Σεισμός & τσουνάμι',knowledgeWeather:'Καιρός & κλίμα',knowledgePower:'Ενέργεια',knowledgeNavigation:'Πλοήγηση & εκκένωση',knowledgePeople:'Άνθρωποι & ζώα',knowledgeRecovery:'Αποκατάσταση',knowledgeGreece:'Ειδικά για Ελλάδα',knowledgeMethod:'Μεθοδολογία πηγών'
});
const V7_NAV=[['knowledge','▧']];
{const i=NAV.findIndex(x=>x[0]==='library');NAV.splice(i<0?NAV.length:i,0,...V7_NAV);for(const [id] of V7_NAV){if(!MOBILE_NAV.includes(id)){const m=MOBILE_NAV.indexOf('library');MOBILE_NAV.splice(m<0?MOBILE_NAV.length:m,0,id)}}}
const KNOWLEDGE_DOMAINS=[
 ['knowledgeWater','water drinking sanitation hygiene boil sewer'],['knowledgeFood','food refrigerator freezer meals allergy'],['knowledgeMedical','medication medical bleeding burn choking heat hypothermia'],['knowledgeCare','infant formula breastfeeding diabetes insulin epilepsy dialysis oxygen CPAP pregnancy specialist'],['knowledgeHazmat','radiation radiological chemical contamination shelter'],['knowledgeInfrastructure','utility restoration heater pipes repair fuel charging dependency'],['knowledgeHousehold','hygiene handwashing laundry bedding clothing foot apartment high-rise rationing'],['knowledgeFire','wildfire smoke fire ash'],['knowledgeEarth','earthquake aftershock tsunami flood'],['knowledgeWeather','lightning wind heat cold snow'],['knowledgePower','generator carbon monoxide battery power'],['knowledgeNavigation','navigation waypoint vehicle evacuation route'],['knowledgePeople','accessibility children older adults pets service animals'],['knowledgeRecovery','recovery evidence insurance expense damage'],['knowledgeGreece','Greece 112 island apartment coastal mountain'],['knowledgeMethod','source anchors methodology']
];
const RISK_KNOWLEDGE_QUERIES={wildfire:['wildfire','smoke','ash','evacuation'],flood:['flood','floodwater','sewage','well','drying'],earthquake:['earthquake','aftershock','tsunami','falling','utility'],outage:['blackout','power','generator','battery','charging','refrigerator','lighting'],heat:['heat','cooling','water','older-adults'],cold:['cold','snow','freeze','heater','clothing','bedding'],evacuation:['evacuation','route','vehicle','walking','bicycle','reunification'],isolation:['isolation','resupply','supply','inventory','food','water','medication']};
function v7LangFolder(){return lang==='el'?'GR':'EN'}
function v7KnowledgeFiles(){const part=`V7 Knowledge Compendium/${v7LangFolder()}/`;return (libraryCache||[]).filter(f=>f.path.startsWith(part)&&f.name.endsWith('.md'))}
function v7KnowledgeKey(path){return String(path||'').split('/').pop()}
function v7ProgressMap(){return new Map((state.knowledge_progress||[]).map(x=>[x.path,x]))}
function v7ProgressFor(path){return v7ProgressMap().get(v7KnowledgeKey(path))||null}
function v7StatusLabel(status){return status==='reviewed'?tx('knowledgeReviewed'):status==='review-later'?tx('knowledgeLater'):tx('knowledgeUnreviewed')}
async function ensureKnowledgeLibrary(){if(!libraryCache.length){const d=await api('/api/library');libraryCache=d.files||[];const g=$('#libraryGrid');if(g)g.dataset.root=d.root||''}}
function renderKnowledgeDomains(){const root=$('#knowledgeDomains');if(!root)return;root.innerHTML=KNOWLEDGE_DOMAINS.map(([label,q])=>`<button class="card quick-card" onclick="knowledgePreset('${arg(q)}')"><strong>${esc(tx(label))}</strong><small>${esc(q.split(' ').slice(0,4).join(' · '))}</small></button>`).join('')}
function v7RecommendedFiles(){const flags=state.risk_flags||[];if(!flags.length)return[];const tokens=[...new Set(flags.flatMap(r=>RISK_KNOWLEDGE_QUERIES[r]||[]))];const scored=v7KnowledgeFiles().filter(f=>!f.name.startsWith('00-')).map(f=>{const n=f.name.toLowerCase();let score=0;for(const t of tokens)if(n.includes(t))score+=t.length>7?3:2;return [score,f]}).filter(x=>x[0]>0);scored.sort((a,b)=>b[0]-a[0]||a[1].name.localeCompare(b[1].name));return scored.slice(0,18).map(x=>x[1])}
function renderKnowledgeRecommended(){const root=$('#knowledgeRecommended');if(!root)return;const files=v7RecommendedFiles();if(!(state.risk_flags||[]).length){root.innerHTML=`<div class="empty">${esc(tx('knowledgeRecommendedNone'))}</div>`;return}root.innerHTML=files.length?`<div class="results">${files.map(v7ResultCard).join('')}</div>`:`<div class="empty">${esc(tx('knowledgeNoResults'))}</div>`}
function renderKnowledgeProgress(){const root=$('#knowledgeProgress');if(!root)return;const files=v7KnowledgeFiles(),pm=v7ProgressMap(),reviewed=files.filter(f=>pm.get(f.name)?.status==='reviewed'),later=files.filter(f=>pm.get(f.name)?.status==='review-later');const rows=[...later,...reviewed].slice(0,80);root.innerHTML=rows.length?`<div class="results">${rows.map(f=>{const p=pm.get(f.name);return `<div class="result"><div class="toolbar"><div class="grow"><strong>${esc(f.name.replace(/\.md$/,''))}</strong><div class="meta"><span class="pill">${esc(v7StatusLabel(p.status))}</span>${p.last_review?`<span class="pill">${esc(p.last_review)}</span>`:''}</div></div><button class="btn" onclick="readLibrary(decodeURIComponent('${arg(f.path)}'))">${esc(tx('read'))}</button><button class="btn danger small" onclick="setKnowledgeStatus(decodeURIComponent('${arg(f.path)}'),'')">×</button></div></div>`}).join('')}</div>`:`<div class="empty">${esc(tx('knowledgeUnreviewed'))}</div>`}
function renderKnowledgeStats(){const root=$('#knowledgeStats');if(!root)return;const files=v7KnowledgeFiles(),pm=v7ProgressMap(),reviewed=files.filter(f=>pm.get(f.name)?.status==='reviewed').length,later=files.filter(f=>pm.get(f.name)?.status==='review-later').length,unreviewed=Math.max(0,files.length-reviewed-later),recommended=v7RecommendedFiles(),riskReviewed=recommended.filter(f=>pm.get(f.name)?.status==='reviewed').length;root.innerHTML=`<div class="mini-stat"><small>${esc(tx('knowledgeChapters'))}</small><strong>${fmt(files.length)}</strong></div><div class="mini-stat"><small>${esc(tx('knowledgeReviewed'))}</small><strong>${fmt(reviewed)}</strong></div><div class="mini-stat"><small>${esc(tx('knowledgeLater'))}</small><strong>${fmt(later)}</strong></div><div class="mini-stat"><small>${esc(tx('knowledgeUnreviewed'))}</small><strong>${fmt(unreviewed)}</strong></div><div class="mini-stat"><small>${esc(tx('knowledgeRiskCoverage'))}</small><strong>${fmt(riskReviewed)}/${fmt(recommended.length)}</strong></div>`}
function v7ResultCard(x){const p=v7ProgressFor(x.path),status=p?.status||'';return `<div class="result"><div class="toolbar"><div class="grow"><h3>${esc(x.name.replace(/\.md$/,''))}</h3><div class="meta"><span class="pill">${esc(x.size_human||'')}</span><span class="pill">${esc(v7StatusLabel(status))}</span></div></div><button class="btn primary" onclick="readLibrary(decodeURIComponent('${arg(x.path)}'))">${esc(tx('read'))}</button><button class="btn" onclick="setKnowledgeStatus(decodeURIComponent('${arg(x.path)}'),'reviewed')">${esc(tx('markReviewed'))}</button><button class="btn" onclick="setKnowledgeStatus(decodeURIComponent('${arg(x.path)}'),'review-later')">${esc(tx('markLater'))}</button></div>${x.snippet?`<p>${esc(x.snippet)}</p>`:''}</div>`}
async function refreshKnowledgeAtlas(){try{await ensureKnowledgeLibrary();renderKnowledgeDomains();renderKnowledgeStats();renderKnowledgeRecommended();renderKnowledgeProgress();const root=$('#knowledgeResults');if(root&&!root.dataset.searched)root.innerHTML=v7KnowledgeFiles().slice(0,12).map(v7ResultCard).join('')||`<div class="empty">${esc(tx('knowledgeNoResults'))}</div>`}catch(e){const r=$('#knowledgeResults');if(r)r.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function searchKnowledgeAtlas(){const root=$('#knowledgeResults'),q=($('#knowledgeQuery')?.value||'').trim();if(!root)return;if(q.length<2){root.innerHTML=`<div class="empty">${esc(tx('knowledgeNeedQuery'))}</div>`;return}root.dataset.searched='1';root.innerHTML=`<div class="empty">${esc(tx('loading'))}</div>`;try{const prefix=`V7 Knowledge Compendium/${v7LangFolder()}`,d=await api(`/api/library/search?q=${encodeURIComponent(q)}&limit=250&prefix=${encodeURIComponent(prefix)}`),rows=(d.results||[]);root.innerHTML=rows.length?`<div class="results">${rows.map(v7ResultCard).join('')}</div>`:`<div class="empty">${esc(tx('knowledgeNoResults'))}</div>`}catch(e){root.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function knowledgePreset(q){const e=$('#knowledgeQuery');if(e)e.value=q;searchKnowledgeAtlas()}
async function setKnowledgeStatus(path,status){state.knowledge_progress=state.knowledge_progress||[];const key=v7KnowledgeKey(path),i=state.knowledge_progress.findIndex(x=>x.path===key);if(!status){if(i>=0)state.knowledge_progress.splice(i,1)}else{const row={path:key,status,last_review:new Date().toISOString().slice(0,10),notes:i>=0?(state.knowledge_progress[i].notes||''):''};if(i>=0)state.knowledge_progress[i]=row;else state.knowledge_progress.push(row)}await saveState();renderKnowledgeStats();renderKnowledgeRecommended();renderKnowledgeProgress();const root=$('#knowledgeResults');if(root&&root.dataset.searched)searchKnowledgeAtlas()}

function exportKnowledgeQueue(){
  const files=v7RecommendedFiles(),risks=(state.risk_flags||[]).map(x=>RISKS[x]?.[lang]||x);
  const lines=[tx('knowledgeQueueTitle'),'',`${tx('knowledgeQueueRisks')}: ${risks.length?risks.join(', '):'—'}`,''];
  if(!files.length)lines.push(tx('knowledgeQueueEmpty'));
  else files.forEach((f,i)=>{const p=v7ProgressFor(f.path);lines.push(`${i+1}. ${f.name.replace(/\.md$/,'')} — ${v7StatusLabel(p?.status||'')}`)});
  lines.push('',lang==='el'?'Δημιουργήθηκε τοπικά· δεν μεταδόθηκε προφίλ κινδύνου.':'Generated locally; no risk profile was transmitted.');
  downloadBlob(lines.join('\n'),`offline-survival-knowledge-queue-${new Date().toISOString().slice(0,10)}.txt`,'text/plain;charset=utf-8');
}

async function openCompendiumIndex(){try{await ensureKnowledgeLibrary();const path=`V7 Knowledge Compendium/${v7LangFolder()}/00-compendium-index-and-use.md`;await readLibrary(path)}catch(e){toast(e.message)}}
const v7BaseApplyLang=applyLang;
applyLang=function(){v7BaseApplyLang();renderKnowledgeDomains();if(currentSection==='knowledge')refreshKnowledgeAtlas()};
const v7BaseSetTitle=setTitle;
setTitle=function(id){v7BaseSetTitle(id);if(id==='knowledge')$('#pageSub').textContent=tx('knowledgeSub')};
const v7BaseGo=go;
go=function(id){v7BaseGo(id);if(id==='knowledge')refreshKnowledgeAtlas()};
applyLang();
